#!/usr/bin/env bash

flash() {
  local platform="${1}"
  local serial="${2}"
  local address="${3}"

  local wifi_default_pass="racegate"
  local wifi_default_ssid="racegate"

  if [ -z "${RACEGATE_WIFI_CONFIG}" ]; then
    # Unless wifi configuration is overridden by env var
    local wifi_ap_enabled="false"
    if [ "${address}" == "0" ]; then
      # Enable AP
      wifi_ap_enabled="true"
    fi

    RACEGATE_WIFI_CONFIG="${wifi_ap_enabled}:${wifi_default_ssid}:${wifi_default_pass}"
  fi

  RACEGATE_NODE_ADDRESS="${address}"

  export RACEGATE_NODE_ADDRESS
  export RACEGATE_WIFI_CONFIG

  echo "RACEGATE_NODE_ADDRESS=${RACEGATE_NODE_ADDRESS}"
  echo "RACEGATE_WIFI_CONFIG=${RACEGATE_WIFI_CONFIG}"

  cargo espflash \
    --features="${platform}" \
    --speed 1500000 \
    --monitor "${serial}" \
    --partition-table partitions/partitions_singleapp_4MB.csv
}

main() {
  case $1 in
  flash) flash "${2}" "${3}" "${4}";;
  esac
}

main "$@"
